<?php
declare(strict_types=1);
require is_file(__DIR__.'/_enoch/app/bootstrap.php') ? __DIR__.'/_enoch/app/bootstrap.php' : dirname(__DIR__).'/app/bootstrap.php';
use Enoch\Web;
Web::headers();$auth->session();$error='';$setup=(int)$store->query('SELECT COUNT(*) FROM users')->fetchColumn()===0;
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{
        $auth->csrf($_POST['csrf']??'');
        if(($_POST['action']??'')==='logout'){$_SESSION=[];session_regenerate_id(true);header('Location: /');exit;}
        if($setup){$auth->setup($_POST['key']??'',$_POST['name']??'',$_POST['password']??'');$setup=false;}
        if($auth->login($_POST['name']??'',$_POST['password']??'')){header('Location: /');exit;}
        $error='Username or password is incorrect.';
    }catch(Throwable $e){$error=$e instanceof PDOException?'The account database is unavailable.':$e->getMessage();}
}
$user=$auth->user();$e=Web::escape(...);
?><!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Enoch · Infrastructure</title><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/app.css"><?php if($user):?><meta name="csrf-token" content="<?=$e($_SESSION['csrf'])?>"><script src="/assets/app.js" defer></script><?php endif?></head>
<body data-role="<?=$e($user['role']??'')?>" data-read-only="<?=$config->get('APP_READ_ONLY')==='1'?'true':'false'?>">
<?php if(!$user):?>
<main class="login"><div class="login-story"><a class="brand" href="/">e<span>enoch</span><i>●</i></a><div><p class="eyebrow">SCHAEFCHENS / INFRASTRUCTURE</p><h1>Faithful in<br>the little things.</h1><p>A place to tend what we have been given.<br>In service to the body of Christ.</p></div><small>“Let all things be done with charity.” · 1 Corinthians 16:14 (KJV)</small></div><div class="login-side"><form method="post" class="login-form"><span class="eyebrow">TEAM ACCESS</span><h2><?=$setup?'Set up your workspace':'Welcome back.'?></h2><p><?=$setup?'Create the first administrator using the setup key from the private .env file.':'Sign in to manage your infrastructure.'?></p><?php if($error):?><div class="error" role="alert"><?=$e($error)?></div><?php endif?><input type="hidden" name="csrf" value="<?=$e($_SESSION['csrf'])?>"><?php if($setup):?><label>Setup key<input type="password" name="key" autocomplete="off" required></label><?php endif?><label>Username<input name="name" autocomplete="username" minlength="3" maxlength="80" required autofocus></label><label>Password<input type="password" name="password" autocomplete="<?=$setup?'new-password':'current-password'?>" <?=$setup?'minlength="12" maxlength="72"':''?> required></label><button class="primary" type="submit"><?=$setup?'Create administrator':'Sign in'?> <span>→</span></button><small>One body. Many members. Shared stewardship.</small></form></div></main>
<?php else:?>
<div class="shell"><aside class="sidebar"><a class="brand" href="/">e<span>enoch</span><i>●</i></a><p class="workspace">SCHAEFCHENS<br><span>A place of stewardship</span></p><nav aria-label="Main navigation"><button class="nav active" data-page="servers"><span>▦</span> Overview</button><button class="nav" data-page="activity"><span>≋</span> Activity</button><button class="nav" data-page="team"><span>♧</span> Team & account</button></nav><div class="sidebar-bottom"><span class="avatar"><?=$e(strtoupper(substr($user['name'],0,1)))?></span><div><strong><?=$e($user['name'])?></strong><small><?=$e(ucfirst($user['role']))?></small></div><form method="post"><input type="hidden" name="csrf" value="<?=$e($_SESSION['csrf'])?>"><input type="hidden" name="action" value="logout"><button class="logout" aria-label="Sign out" title="Sign out">↗</button></form></div></aside>
<main class="main"><header class="topbar"><span>Workspace <b>/</b> <strong id="page-label">Overview</strong></span><span id="refresh-label">Connecting…</span></header><div class="content"><div id="notice" class="notice" role="status" hidden></div>
<section id="page-servers" class="page"><div class="page-heading"><div><p class="eyebrow">FAITHFUL STEWARDSHIP</p><h1>Tend what is entrusted.</h1><p>Care for the tools that serve our fellowship.</p></div><button id="refresh" class="secondary">↻ &nbsp; Refresh</button></div><div class="summary"><div><span class="summary-label">SERVERS ONLINE</span><strong id="online-count">— <small>/ 2</small></strong></div><div><span class="summary-label">SAVED SNAPSHOTS</span><strong id="snapshot-count">—</strong></div><div><span class="summary-label">SCHEDULER</span><strong class="small" id="cron-status">Waiting for first run</strong></div></div><div class="section-heading"><h2>Servers <span id="service-count">2</span></h2><span>Persistent IPs · Restore from snapshot</span></div><div id="servers" class="server-grid"><div class="loading">Loading your servers…</div></div><div class="section-heading"><h2>Scheduled maintenance</h2><span>One cron, multiple tasks</span></div><div id="tasks"></div><div class="section-heading"><h2>Recent operations</h2><button class="text-button" data-page="activity">View activity →</button></div><div id="jobs"></div><p class="footnote">“Moreover it is required in stewards, that a man be found faithful.” · 1 Corinthians 4:2 (KJV)<br>Keep this page open while an operation runs. If you leave, the scheduler continues it on its next visit. Each saved stop releases the VM; snapshots and persistent IPs remain billable.</p></section>
<section id="page-activity" class="page" hidden><div class="page-heading"><div><p class="eyebrow">THE WORKSPACE LOG</p><h1>A record of our stewardship.</h1><p>Operations, scheduled checks and the people behind them.</p></div></div><div id="audit"></div></section>
<section id="page-team" class="page" hidden><div class="page-heading"><div><p class="eyebrow">PEOPLE & ACCESS</p><h1>Many members. One body.</h1><p>Each person has a part to play in caring for our shared work.</p></div></div><div class="team-grid"><div><div id="users"></div><?php if($user['role']==='admin'):?><form id="add-user" class="panel"><h2>Add a teammate</h2><label>Username<input name="name" required minlength="3" maxlength="80" autocomplete="off"></label><label>Temporary password<input name="password" type="password" required minlength="12" maxlength="72" autocomplete="new-password"></label><label>Access<select name="role"><option value="operator">Operator · start and stop servers</option><option value="viewer">Viewer · status and activity</option><option value="admin">Administrator · manage the team</option></select></label><button class="primary">Create account</button><p class="muted">Share the password privately. Your teammate can change it after signing in.</p></form><?php endif?></div><form id="password" class="panel"><h2>Change your password</h2><label>Current password<input name="current" type="password" autocomplete="current-password" required></label><label>New password<input name="password" type="password" minlength="12" maxlength="72" autocomplete="new-password" required></label><button class="secondary">Update password</button></form></div><form method="post" class="account-signout"><input type="hidden" name="csrf" value="<?=$e($_SESSION['csrf'])?>"><input type="hidden" name="action" value="logout"><button class="secondary">Sign out of Enoch ↗</button></form></section>
</div></main></div>
<dialog id="confirm"><form method="dialog"><button class="dialog-close" aria-label="Close">×</button></form><p class="eyebrow">SERVER OPERATION</p><h2 id="confirm-title"></h2><p id="confirm-text"></p><div class="confirm-note" id="confirm-note"></div><div class="dialog-actions"><button id="cancel" class="secondary">Cancel</button><button id="proceed" class="primary">Continue</button></div></dialog>
<?php endif?></body></html>
